# Generated by Django 4.2.4 on 2023-08-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articalmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
